# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5d7f87aa33802d02b496148727ede58a"
application_url = "https://eu-withdrawal-easy.fly.dev"
embedded = true
name = "EU withdrawal easy"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = " write_products,read_customers,write_metaobjects,write_metaobject_definitions,read_orders,write_orders,write_returns,write_merchant_managed_fulfillment_orders,write_third_party_fulfillment_orders,read_locations"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [" https://eu-withdrawal-easy.fly.dev/auth"]

[build]
automatically_update_urls_on_dev = true
