# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3665659df10c303b676289189c70b417"
application_url = "https://example.com"
embedded = true
name = "EU RM"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions,read_orders,write_orders,write_returns,write_merchant_managed_fulfillment_orders,write_third_party_fulfillment_orders,read_customers"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
