// Translatable copy for the three customer-facing emails, in every language the
// form offers. The registry (registry.js) feeds each language's strings through
// the same builder functions, so the English default and every translation
// share one structure — only the words change. Pure data, no imports.
//
// Backtick strings so apostrophes and the mailto anchor's quotes need no
// escaping. {{ liquid.paths }} are filled at render time (variables.js); leave
// them exactly as written.
//
// `contact` is one <a> away from plain text — keep the anchor markup intact and
// only translate the words around it.

export const EMAIL_STRING_LOCALES = ["de", "fr", "nl", "it", "es", "pl", "sv"];

const link = `<a href="mailto:{{ shop.email }}" style="color:#2c6ecb">{{ shop.email }}</a>`;

export const EMAIL_STRINGS = {
  en: {
    footer: `This email was sent by EU Withdrawly on behalf of {{ shop.name }}.`,
    labels: {
      referenceNumber: `Reference number`,
      orderNumber: `Order number`,
      submittedOn: `Submitted on`,
      status: `Status`,
      reason: `Reason`,
    },
    contact: `Questions about your request? Contact {{ shop.name }} at ${link}, or simply reply to this email.`,
    confirmation: {
      subject: `We've received your withdrawal request — order {{ order.name }}`,
      heading: `Your withdrawal request has been received`,
      callout: `Thanks — your withdrawal request has been received and is now being reviewed.`,
      intro: `Hi {{ customer.first_name }}, thank you for contacting {{ shop.name }}. This email confirms that we've received your withdrawal request. You have the right to withdraw from your purchase under EU consumer law, and we'll process your request as quickly as possible.`,
      itemsHeading: `Items you're withdrawing`,
      nextHeading: `What happens next`,
      nextSteps: [
        `Our team will review your request.`,
        `We'll email you the next steps, including return instructions if any items need to be sent back.`,
        `Any refund you're due will be issued in line with EU consumer law once your withdrawal is processed.`,
      ],
      smallPrint: `If you didn't make this request, or anything looks wrong, please let us know straight away.`,
    },
    approved: {
      subject: `Your withdrawal request for order {{ order.name }} has been approved`,
      heading: `Your withdrawal request has been approved`,
      callout: `Good news — your withdrawal request has been approved.`,
      intro: `Hi {{ customer.first_name }}, we've reviewed your request and approved your withdrawal from order {{ order.name }}. Here's what this means and what happens next.`,
      itemsHeading: `Approved items`,
      refundHeading: `Your refund`,
      refund: `We'll refund your payment to your original payment method within 14 days, as required by EU consumer law. Where you've withdrawn from your whole order, this includes the standard delivery cost.`,
      returnHeading: `Returning your items`,
      returnText: `If your order has already been delivered, please keep the items in their original condition. We'll send you separate return instructions — including the return address and who covers return shipping — and ask that you send the items back within 14 days. Your refund is completed once we've received the items back, or you've provided proof that you've returned them.`,
    },
    rejected: {
      subject: `Update on your withdrawal request for order {{ order.name }}`,
      heading: `Update on your withdrawal request`,
      callout: `After reviewing your request, we're unable to approve this withdrawal.`,
      intro: `Hi {{ customer.first_name }}, thank you for contacting {{ shop.name }}. We've carefully reviewed your withdrawal request for order {{ order.name }}, and unfortunately we're unable to approve it on this occasion.`,
      exemptions: `This can happen when a request falls outside the statutory 14-day withdrawal period, or when the items are exempt from the right of withdrawal — for example personalised or made-to-order goods, sealed health or hygiene products that have been unsealed, or perishable items.`,
      itemsHeading: `Items in this request`,
      appeal: `If you'd like more detail on the reason for this decision, or you believe it may be a mistake, please get in touch — we'll be glad to help. This decision doesn't affect your statutory consumer rights.`,
    },
  },

  de: {
    footer: `Diese E-Mail wurde von EU Withdrawly im Auftrag von {{ shop.name }} gesendet.`,
    labels: {
      referenceNumber: `Referenznummer`,
      orderNumber: `Bestellnummer`,
      submittedOn: `Eingereicht am`,
      status: `Status`,
      reason: `Grund`,
    },
    contact: `Fragen zu Ihrem Antrag? Kontaktieren Sie {{ shop.name }} unter ${link} oder antworten Sie einfach auf diese E-Mail.`,
    confirmation: {
      subject: `Wir haben Ihren Widerrufsantrag erhalten — Bestellung {{ order.name }}`,
      heading: `Ihr Widerrufsantrag ist eingegangen`,
      callout: `Vielen Dank — Ihr Widerrufsantrag ist eingegangen und wird nun geprüft.`,
      intro: `Hallo {{ customer.first_name }}, vielen Dank, dass Sie sich an {{ shop.name }} gewandt haben. Diese E-Mail bestätigt, dass wir Ihren Widerrufsantrag erhalten haben. Sie haben nach EU-Verbraucherrecht das Recht, von Ihrem Kauf zurückzutreten, und wir werden Ihren Antrag so schnell wie möglich bearbeiten.`,
      itemsHeading: `Artikel, die Sie widerrufen`,
      nextHeading: `Wie es weitergeht`,
      nextSteps: [
        `Unser Team wird Ihren Antrag prüfen.`,
        `Wir senden Ihnen die nächsten Schritte per E-Mail, einschließlich Rücksendeanweisungen, falls Artikel zurückgesendet werden müssen.`,
        `Eine Ihnen zustehende Rückerstattung wird nach EU-Verbraucherrecht ausgestellt, sobald Ihr Widerruf bearbeitet wurde.`,
      ],
      smallPrint: `Falls Sie diesen Antrag nicht gestellt haben oder etwas nicht korrekt erscheint, lassen Sie es uns bitte umgehend wissen.`,
    },
    approved: {
      subject: `Ihr Widerrufsantrag für Bestellung {{ order.name }} wurde genehmigt`,
      heading: `Ihr Widerrufsantrag wurde genehmigt`,
      callout: `Gute Nachrichten — Ihr Widerrufsantrag wurde genehmigt.`,
      intro: `Hallo {{ customer.first_name }}, wir haben Ihren Antrag geprüft und Ihren Widerruf von Bestellung {{ order.name }} genehmigt. Hier erfahren Sie, was das bedeutet und wie es weitergeht.`,
      itemsHeading: `Genehmigte Artikel`,
      refundHeading: `Ihre Rückerstattung`,
      refund: `Wir erstatten Ihre Zahlung innerhalb von 14 Tagen auf Ihr ursprüngliches Zahlungsmittel zurück, wie es das EU-Verbraucherrecht vorschreibt. Wenn Sie von Ihrer gesamten Bestellung zurückgetreten sind, umfasst dies die Standardversandkosten.`,
      returnHeading: `Rücksendung Ihrer Artikel`,
      returnText: `Falls Ihre Bestellung bereits geliefert wurde, bewahren Sie die Artikel bitte im Originalzustand auf. Wir senden Ihnen gesonderte Rücksendeanweisungen — einschließlich der Rücksendeadresse und wer die Rücksendekosten trägt — und bitten Sie, die Artikel innerhalb von 14 Tagen zurückzusenden. Ihre Rückerstattung wird abgeschlossen, sobald wir die Artikel zurückerhalten haben oder Sie einen Nachweis über die Rücksendung erbracht haben.`,
    },
    rejected: {
      subject: `Aktualisierung zu Ihrem Widerrufsantrag für Bestellung {{ order.name }}`,
      heading: `Aktualisierung zu Ihrem Widerrufsantrag`,
      callout: `Nach Prüfung Ihres Antrags können wir diesen Widerruf leider nicht genehmigen.`,
      intro: `Hallo {{ customer.first_name }}, vielen Dank, dass Sie sich an {{ shop.name }} gewandt haben. Wir haben Ihren Widerrufsantrag für Bestellung {{ order.name }} sorgfältig geprüft und können ihn in diesem Fall leider nicht genehmigen.`,
      exemptions: `Dies kann vorkommen, wenn ein Antrag außerhalb der gesetzlichen 14-tägigen Widerrufsfrist liegt oder wenn die Artikel vom Widerrufsrecht ausgenommen sind — zum Beispiel personalisierte oder maßgefertigte Waren, versiegelte Gesundheits- oder Hygieneprodukte, deren Versiegelung entfernt wurde, oder verderbliche Waren.`,
      itemsHeading: `Artikel in diesem Antrag`,
      appeal: `Wenn Sie weitere Einzelheiten zur Begründung dieser Entscheidung wünschen oder glauben, dass es sich um einen Fehler handelt, nehmen Sie bitte Kontakt mit uns auf — wir helfen Ihnen gerne. Diese Entscheidung berührt Ihre gesetzlichen Verbraucherrechte nicht.`,
    },
  },

  fr: {
    footer: `Cet e-mail a été envoyé par EU Withdrawly au nom de {{ shop.name }}.`,
    labels: {
      referenceNumber: `Numéro de référence`,
      orderNumber: `Numéro de commande`,
      submittedOn: `Soumis le`,
      status: `Statut`,
      reason: `Motif`,
    },
    contact: `Des questions sur votre demande ? Contactez {{ shop.name }} à l'adresse ${link}, ou répondez simplement à cet e-mail.`,
    confirmation: {
      subject: `Nous avons reçu votre demande de rétractation — commande {{ order.name }}`,
      heading: `Votre demande de rétractation a bien été reçue`,
      callout: `Merci — votre demande de rétractation a été reçue et est en cours d'examen.`,
      intro: `Bonjour {{ customer.first_name }}, merci d'avoir contacté {{ shop.name }}. Cet e-mail confirme que nous avons bien reçu votre demande de rétractation. Vous disposez du droit de vous rétracter de votre achat en vertu du droit européen de la consommation, et nous traiterons votre demande dans les meilleurs délais.`,
      itemsHeading: `Articles concernés par votre rétractation`,
      nextHeading: `Prochaines étapes`,
      nextSteps: [
        `Notre équipe examinera votre demande.`,
        `Nous vous enverrons par e-mail les prochaines étapes, y compris les instructions de retour si certains articles doivent être renvoyés.`,
        `Tout remboursement qui vous est dû sera effectué conformément au droit européen de la consommation une fois votre rétractation traitée.`,
      ],
      smallPrint: `Si vous n'êtes pas à l'origine de cette demande, ou si quelque chose vous semble incorrect, veuillez nous en informer immédiatement.`,
    },
    approved: {
      subject: `Votre demande de rétractation pour la commande {{ order.name }} a été approuvée`,
      heading: `Votre demande de rétractation a été approuvée`,
      callout: `Bonne nouvelle — votre demande de rétractation a été approuvée.`,
      intro: `Bonjour {{ customer.first_name }}, nous avons examiné votre demande et approuvé votre rétractation pour la commande {{ order.name }}. Voici ce que cela signifie et les prochaines étapes.`,
      itemsHeading: `Articles approuvés`,
      refundHeading: `Votre remboursement`,
      refund: `Nous rembourserons votre paiement sur votre moyen de paiement d'origine dans un délai de 14 jours, comme l'exige le droit européen de la consommation. Si vous vous êtes rétracté de la totalité de votre commande, cela inclut les frais de livraison standard.`,
      returnHeading: `Retour de vos articles`,
      returnText: `Si votre commande a déjà été livrée, veuillez conserver les articles dans leur état d'origine. Nous vous enverrons des instructions de retour distinctes — y compris l'adresse de retour et qui prend en charge les frais de retour — et vous demandons de renvoyer les articles dans un délai de 14 jours. Votre remboursement est finalisé une fois que nous avons reçu les articles, ou que vous avez fourni une preuve de leur renvoi.`,
    },
    rejected: {
      subject: `Mise à jour concernant votre demande de rétractation pour la commande {{ order.name }}`,
      heading: `Mise à jour concernant votre demande de rétractation`,
      callout: `Après examen de votre demande, nous ne sommes pas en mesure d'approuver cette rétractation.`,
      intro: `Bonjour {{ customer.first_name }}, merci d'avoir contacté {{ shop.name }}. Nous avons examiné attentivement votre demande de rétractation pour la commande {{ order.name }} et, malheureusement, nous ne sommes pas en mesure de l'approuver cette fois-ci.`,
      exemptions: `Cela peut se produire lorsqu'une demande est présentée en dehors du délai légal de rétractation de 14 jours, ou lorsque les articles sont exclus du droit de rétractation — par exemple des biens personnalisés ou fabriqués sur mesure, des produits de santé ou d'hygiène scellés qui ont été descellés, ou des biens périssables.`,
      itemsHeading: `Articles de cette demande`,
      appeal: `Si vous souhaitez plus de détails sur le motif de cette décision, ou si vous pensez qu'il s'agit d'une erreur, n'hésitez pas à nous contacter — nous serons ravis de vous aider. Cette décision n'affecte pas vos droits légaux en tant que consommateur.`,
    },
  },

  nl: {
    footer: `Deze e-mail is verzonden door EU Withdrawly namens {{ shop.name }}.`,
    labels: {
      referenceNumber: `Referentienummer`,
      orderNumber: `Bestelnummer`,
      submittedOn: `Ingediend op`,
      status: `Status`,
      reason: `Reden`,
    },
    contact: `Vragen over uw verzoek? Neem contact op met {{ shop.name }} via ${link} of beantwoord gewoon deze e-mail.`,
    confirmation: {
      subject: `We hebben uw herroepingsverzoek ontvangen — bestelling {{ order.name }}`,
      heading: `Uw herroepingsverzoek is ontvangen`,
      callout: `Bedankt — uw herroepingsverzoek is ontvangen en wordt nu beoordeeld.`,
      intro: `Hallo {{ customer.first_name }}, bedankt dat u contact hebt opgenomen met {{ shop.name }}. Deze e-mail bevestigt dat we uw herroepingsverzoek hebben ontvangen. U hebt op grond van het EU-consumentenrecht het recht om uw aankoop te herroepen, en we zullen uw verzoek zo snel mogelijk verwerken.`,
      itemsHeading: `Artikelen die u herroept`,
      nextHeading: `Wat er nu gebeurt`,
      nextSteps: [
        `Ons team beoordeelt uw verzoek.`,
        `We e-mailen u de volgende stappen, inclusief retourinstructies als er artikelen teruggestuurd moeten worden.`,
        `Een eventuele terugbetaling waar u recht op hebt, wordt volgens het EU-consumentenrecht uitgevoerd zodra uw herroeping is verwerkt.`,
      ],
      smallPrint: `Als u dit verzoek niet hebt ingediend, of als er iets niet klopt, laat het ons dan meteen weten.`,
    },
    approved: {
      subject: `Uw herroepingsverzoek voor bestelling {{ order.name }} is goedgekeurd`,
      heading: `Uw herroepingsverzoek is goedgekeurd`,
      callout: `Goed nieuws — uw herroepingsverzoek is goedgekeurd.`,
      intro: `Hallo {{ customer.first_name }}, we hebben uw verzoek beoordeeld en uw herroeping van bestelling {{ order.name }} goedgekeurd. Dit is wat dat betekent en wat er nu gebeurt.`,
      itemsHeading: `Goedgekeurde artikelen`,
      refundHeading: `Uw terugbetaling`,
      refund: `We betalen uw betaling binnen 14 dagen terug via uw oorspronkelijke betaalmethode, zoals vereist door het EU-consumentenrecht. Als u uw hele bestelling hebt herroepen, zijn de standaard verzendkosten hierbij inbegrepen.`,
      returnHeading: `Uw artikelen retourneren`,
      returnText: `Als uw bestelling al is geleverd, bewaar de artikelen dan in hun oorspronkelijke staat. We sturen u aparte retourinstructies — inclusief het retouradres en wie de retourkosten draagt — en vragen u de artikelen binnen 14 dagen terug te sturen. Uw terugbetaling wordt afgerond zodra we de artikelen retour hebben ontvangen, of u een bewijs van verzending hebt aangeleverd.`,
    },
    rejected: {
      subject: `Update over uw herroepingsverzoek voor bestelling {{ order.name }}`,
      heading: `Update over uw herroepingsverzoek`,
      callout: `Na beoordeling van uw verzoek kunnen we deze herroeping helaas niet goedkeuren.`,
      intro: `Hallo {{ customer.first_name }}, bedankt dat u contact hebt opgenomen met {{ shop.name }}. We hebben uw herroepingsverzoek voor bestelling {{ order.name }} zorgvuldig beoordeeld en kunnen het deze keer helaas niet goedkeuren.`,
      exemptions: `Dit kan gebeuren wanneer een verzoek buiten de wettelijke herroepingstermijn van 14 dagen valt, of wanneer de artikelen zijn uitgesloten van het herroepingsrecht — bijvoorbeeld gepersonaliseerde of op maat gemaakte goederen, verzegelde gezondheids- of hygiëneproducten waarvan de verzegeling is verbroken, of bederfelijke goederen.`,
      itemsHeading: `Artikelen in dit verzoek`,
      appeal: `Als u meer details wilt over de reden van deze beslissing, of als u denkt dat het een vergissing is, neem dan contact met ons op — we helpen u graag. Deze beslissing doet geen afbreuk aan uw wettelijke consumentenrechten.`,
    },
  },

  it: {
    footer: `Questa e-mail è stata inviata da EU Withdrawly per conto di {{ shop.name }}.`,
    labels: {
      referenceNumber: `Numero di riferimento`,
      orderNumber: `Numero d'ordine`,
      submittedOn: `Inviata il`,
      status: `Stato`,
      reason: `Motivo`,
    },
    contact: `Domande sulla tua richiesta? Contatta {{ shop.name }} all'indirizzo ${link} oppure rispondi semplicemente a questa e-mail.`,
    confirmation: {
      subject: `Abbiamo ricevuto la tua richiesta di recesso — ordine {{ order.name }}`,
      heading: `La tua richiesta di recesso è stata ricevuta`,
      callout: `Grazie — la tua richiesta di recesso è stata ricevuta ed è in fase di revisione.`,
      intro: `Ciao {{ customer.first_name }}, grazie per aver contattato {{ shop.name }}. Questa e-mail conferma che abbiamo ricevuto la tua richiesta di recesso. Hai il diritto di recedere dal tuo acquisto ai sensi del diritto europeo dei consumatori, ed elaboreremo la tua richiesta il prima possibile.`,
      itemsHeading: `Articoli oggetto del recesso`,
      nextHeading: `Cosa succede ora`,
      nextSteps: [
        `Il nostro team esaminerà la tua richiesta.`,
        `Ti invieremo via e-mail i passaggi successivi, incluse le istruzioni per il reso se alcuni articoli devono essere restituiti.`,
        `Qualsiasi rimborso a te dovuto sarà emesso in conformità al diritto europeo dei consumatori una volta elaborato il recesso.`,
      ],
      smallPrint: `Se non hai effettuato tu questa richiesta, o se qualcosa non ti sembra corretto, faccelo sapere subito.`,
    },
    approved: {
      subject: `La tua richiesta di recesso per l'ordine {{ order.name }} è stata approvata`,
      heading: `La tua richiesta di recesso è stata approvata`,
      callout: `Buone notizie — la tua richiesta di recesso è stata approvata.`,
      intro: `Ciao {{ customer.first_name }}, abbiamo esaminato la tua richiesta e approvato il tuo recesso dall'ordine {{ order.name }}. Ecco cosa significa e cosa succede ora.`,
      itemsHeading: `Articoli approvati`,
      refundHeading: `Il tuo rimborso`,
      refund: `Rimborseremo il tuo pagamento sul metodo di pagamento originale entro 14 giorni, come richiesto dal diritto europeo dei consumatori. Se hai receduto dall'intero ordine, questo include i costi di spedizione standard.`,
      returnHeading: `Restituzione degli articoli`,
      returnText: `Se il tuo ordine è già stato consegnato, conserva gli articoli nelle loro condizioni originali. Ti invieremo istruzioni di reso separate — inclusi l'indirizzo di reso e chi copre le spese di spedizione del reso — e ti chiediamo di restituire gli articoli entro 14 giorni. Il tuo rimborso viene completato una volta ricevuti gli articoli, oppure quando hai fornito la prova di averli restituiti.`,
    },
    rejected: {
      subject: `Aggiornamento sulla tua richiesta di recesso per l'ordine {{ order.name }}`,
      heading: `Aggiornamento sulla tua richiesta di recesso`,
      callout: `Dopo aver esaminato la tua richiesta, non possiamo approvare questo recesso.`,
      intro: `Ciao {{ customer.first_name }}, grazie per aver contattato {{ shop.name }}. Abbiamo esaminato attentamente la tua richiesta di recesso per l'ordine {{ order.name }} e, purtroppo, non possiamo approvarla in questa occasione.`,
      exemptions: `Questo può accadere quando una richiesta viene presentata al di fuori del periodo di recesso legale di 14 giorni, oppure quando gli articoli sono esclusi dal diritto di recesso — ad esempio beni personalizzati o realizzati su misura, prodotti sanitari o igienici sigillati che sono stati aperti, o beni deperibili.`,
      itemsHeading: `Articoli di questa richiesta`,
      appeal: `Se desideri maggiori dettagli sul motivo di questa decisione, o ritieni che si tratti di un errore, contattaci pure — saremo lieti di aiutarti. Questa decisione non pregiudica i tuoi diritti di consumatore previsti dalla legge.`,
    },
  },

  es: {
    footer: `Este correo fue enviado por EU Withdrawly en nombre de {{ shop.name }}.`,
    labels: {
      referenceNumber: `Número de referencia`,
      orderNumber: `Número de pedido`,
      submittedOn: `Enviado el`,
      status: `Estado`,
      reason: `Motivo`,
    },
    contact: `¿Tienes preguntas sobre tu solicitud? Contacta con {{ shop.name }} en ${link} o simplemente responde a este correo.`,
    confirmation: {
      subject: `Hemos recibido tu solicitud de desistimiento — pedido {{ order.name }}`,
      heading: `Tu solicitud de desistimiento se ha recibido`,
      callout: `Gracias — tu solicitud de desistimiento se ha recibido y está en revisión.`,
      intro: `Hola {{ customer.first_name }}, gracias por ponerte en contacto con {{ shop.name }}. Este correo confirma que hemos recibido tu solicitud de desistimiento. Tienes derecho a desistir de tu compra en virtud del derecho de consumo de la UE, y procesaremos tu solicitud lo antes posible.`,
      itemsHeading: `Artículos objeto del desistimiento`,
      nextHeading: `Qué ocurre a continuación`,
      nextSteps: [
        `Nuestro equipo revisará tu solicitud.`,
        `Te enviaremos por correo los siguientes pasos, incluidas las instrucciones de devolución si hay que devolver algún artículo.`,
        `Cualquier reembolso que te corresponda se emitirá conforme al derecho de consumo de la UE una vez procesado tu desistimiento.`,
      ],
      smallPrint: `Si no realizaste esta solicitud, o si algo no parece correcto, háznoslo saber de inmediato.`,
    },
    approved: {
      subject: `Tu solicitud de desistimiento para el pedido {{ order.name }} ha sido aprobada`,
      heading: `Tu solicitud de desistimiento ha sido aprobada`,
      callout: `Buenas noticias — tu solicitud de desistimiento ha sido aprobada.`,
      intro: `Hola {{ customer.first_name }}, hemos revisado tu solicitud y aprobado tu desistimiento del pedido {{ order.name }}. Esto es lo que significa y lo que ocurre a continuación.`,
      itemsHeading: `Artículos aprobados`,
      refundHeading: `Tu reembolso`,
      refund: `Reembolsaremos tu pago a tu método de pago original en un plazo de 14 días, según exige el derecho de consumo de la UE. Si has desistido de todo tu pedido, esto incluye el coste de envío estándar.`,
      returnHeading: `Devolución de tus artículos`,
      returnText: `Si tu pedido ya ha sido entregado, conserva los artículos en su estado original. Te enviaremos instrucciones de devolución por separado —incluida la dirección de devolución y quién asume los gastos de envío de la devolución— y te pedimos que devuelvas los artículos en un plazo de 14 días. Tu reembolso se completa una vez que hayamos recibido los artículos, o cuando hayas aportado una prueba de que los has devuelto.`,
    },
    rejected: {
      subject: `Actualización sobre tu solicitud de desistimiento para el pedido {{ order.name }}`,
      heading: `Actualización sobre tu solicitud de desistimiento`,
      callout: `Tras revisar tu solicitud, no podemos aprobar este desistimiento.`,
      intro: `Hola {{ customer.first_name }}, gracias por ponerte en contacto con {{ shop.name }}. Hemos revisado cuidadosamente tu solicitud de desistimiento para el pedido {{ order.name }} y, lamentablemente, no podemos aprobarla en esta ocasión.`,
      exemptions: `Esto puede ocurrir cuando una solicitud se presenta fuera del plazo legal de desistimiento de 14 días, o cuando los artículos están excluidos del derecho de desistimiento — por ejemplo, bienes personalizados o hechos a medida, productos de salud o higiene precintados que se han abierto, o bienes perecederos.`,
      itemsHeading: `Artículos de esta solicitud`,
      appeal: `Si deseas más detalles sobre el motivo de esta decisión, o crees que puede tratarse de un error, ponte en contacto con nosotros — estaremos encantados de ayudarte. Esta decisión no afecta a tus derechos legales como consumidor.`,
    },
  },

  pl: {
    footer: `Ta wiadomość została wysłana przez EU Withdrawly w imieniu {{ shop.name }}.`,
    labels: {
      referenceNumber: `Numer referencyjny`,
      orderNumber: `Numer zamówienia`,
      submittedOn: `Wysłano`,
      status: `Status`,
      reason: `Powód`,
    },
    contact: `Masz pytania dotyczące wniosku? Skontaktuj się z {{ shop.name }} pod adresem ${link} lub po prostu odpowiedz na tę wiadomość.`,
    confirmation: {
      subject: `Otrzymaliśmy Twój wniosek o odstąpienie — zamówienie {{ order.name }}`,
      heading: `Twój wniosek o odstąpienie został przyjęty`,
      callout: `Dziękujemy — Twój wniosek o odstąpienie został przyjęty i jest obecnie rozpatrywany.`,
      intro: `Cześć {{ customer.first_name }}, dziękujemy za kontakt z {{ shop.name }}. Ta wiadomość potwierdza, że otrzymaliśmy Twój wniosek o odstąpienie od umowy. Zgodnie z prawem konsumenckim UE masz prawo odstąpić od zakupu, a my rozpatrzymy Twój wniosek tak szybko, jak to możliwe.`,
      itemsHeading: `Produkty objęte odstąpieniem`,
      nextHeading: `Co dalej`,
      nextSteps: [
        `Nasz zespół rozpatrzy Twój wniosek.`,
        `Prześlemy Ci e-mailem kolejne kroki, w tym instrukcje zwrotu, jeśli któreś produkty trzeba odesłać.`,
        `Należny Ci zwrot środków zostanie zrealizowany zgodnie z prawem konsumenckim UE po rozpatrzeniu odstąpienia.`,
      ],
      smallPrint: `Jeśli to nie Ty złożyłeś ten wniosek lub coś wygląda nieprawidłowo, daj nam znać jak najszybciej.`,
    },
    approved: {
      subject: `Twój wniosek o odstąpienie dla zamówienia {{ order.name }} został zatwierdzony`,
      heading: `Twój wniosek o odstąpienie został zatwierdzony`,
      callout: `Dobre wiadomości — Twój wniosek o odstąpienie został zatwierdzony.`,
      intro: `Cześć {{ customer.first_name }}, rozpatrzyliśmy Twój wniosek i zatwierdziliśmy odstąpienie od zamówienia {{ order.name }}. Oto co to oznacza i co dalej.`,
      itemsHeading: `Zatwierdzone produkty`,
      refundHeading: `Twój zwrot środków`,
      refund: `Zwrócimy Twoją płatność na pierwotną metodę płatności w ciągu 14 dni, zgodnie z wymogami prawa konsumenckiego UE. Jeśli odstąpiłeś od całego zamówienia, obejmuje to standardowe koszty dostawy.`,
      returnHeading: `Zwrot produktów`,
      returnText: `Jeśli Twoje zamówienie zostało już dostarczone, zachowaj produkty w oryginalnym stanie. Prześlemy Ci oddzielne instrukcje zwrotu — w tym adres zwrotu oraz informację, kto pokrywa koszty zwrotu — i prosimy o odesłanie produktów w ciągu 14 dni. Twój zwrot środków zostanie zakończony po otrzymaniu przez nas produktów lub po przedstawieniu przez Ciebie dowodu ich odesłania.`,
    },
    rejected: {
      subject: `Aktualizacja dotycząca Twojego wniosku o odstąpienie dla zamówienia {{ order.name }}`,
      heading: `Aktualizacja dotycząca Twojego wniosku o odstąpienie`,
      callout: `Po rozpatrzeniu Twojego wniosku nie możemy zatwierdzić tego odstąpienia.`,
      intro: `Cześć {{ customer.first_name }}, dziękujemy za kontakt z {{ shop.name }}. Dokładnie rozpatrzyliśmy Twój wniosek o odstąpienie dla zamówienia {{ order.name }} i niestety nie możemy go tym razem zatwierdzić.`,
      exemptions: `Może się tak zdarzyć, gdy wniosek zostanie złożony po ustawowym 14-dniowym terminie odstąpienia lub gdy produkty są wyłączone z prawa odstąpienia — na przykład towary personalizowane lub wykonane na zamówienie, zapieczętowane produkty zdrowotne lub higieniczne, których opakowanie zostało otwarte, albo towary łatwo psujące się.`,
      itemsHeading: `Produkty w tym wniosku`,
      appeal: `Jeśli chcesz poznać więcej szczegółów dotyczących przyczyny tej decyzji lub uważasz, że to pomyłka, skontaktuj się z nami — chętnie pomożemy. Decyzja ta nie narusza Twoich ustawowych praw konsumenta.`,
    },
  },

  sv: {
    footer: `Detta e-postmeddelande skickades av EU Withdrawly på uppdrag av {{ shop.name }}.`,
    labels: {
      referenceNumber: `Referensnummer`,
      orderNumber: `Ordernummer`,
      submittedOn: `Skickad`,
      status: `Status`,
      reason: `Anledning`,
    },
    contact: `Frågor om din begäran? Kontakta {{ shop.name }} på ${link} eller svara helt enkelt på detta e-postmeddelande.`,
    confirmation: {
      subject: `Vi har tagit emot din ångerbegäran — order {{ order.name }}`,
      heading: `Din ångerbegäran har tagits emot`,
      callout: `Tack — din ångerbegäran har tagits emot och granskas nu.`,
      intro: `Hej {{ customer.first_name }}, tack för att du kontaktade {{ shop.name }}. Detta e-postmeddelande bekräftar att vi har tagit emot din ångerbegäran. Du har rätt att ångra ditt köp enligt EU:s konsumentlagstiftning, och vi behandlar din begäran så snabbt som möjligt.`,
      itemsHeading: `Artiklar du ångrar`,
      nextHeading: `Vad som händer härnäst`,
      nextSteps: [
        `Vårt team granskar din begäran.`,
        `Vi mejlar dig nästa steg, inklusive returinstruktioner om några artiklar behöver skickas tillbaka.`,
        `Eventuell återbetalning du har rätt till görs i enlighet med EU:s konsumentlagstiftning när din ånger har behandlats.`,
      ],
      smallPrint: `Om du inte gjorde denna begäran, eller om något ser fel ut, hör av dig till oss direkt.`,
    },
    approved: {
      subject: `Din ångerbegäran för order {{ order.name }} har godkänts`,
      heading: `Din ångerbegäran har godkänts`,
      callout: `Goda nyheter — din ångerbegäran har godkänts.`,
      intro: `Hej {{ customer.first_name }}, vi har granskat din begäran och godkänt att du ångrar order {{ order.name }}. Så här går det till och vad som händer härnäst.`,
      itemsHeading: `Godkända artiklar`,
      refundHeading: `Din återbetalning`,
      refund: `Vi återbetalar din betalning till din ursprungliga betalningsmetod inom 14 dagar, enligt EU:s konsumentlagstiftning. Om du har ångrat hela din order ingår standardfraktkostnaden.`,
      returnHeading: `Returnera dina artiklar`,
      returnText: `Om din order redan har levererats, behåll artiklarna i originalskick. Vi skickar separata returinstruktioner till dig — inklusive returadress och vem som står för returfrakten — och ber dig skicka tillbaka artiklarna inom 14 dagar. Din återbetalning slutförs när vi har fått tillbaka artiklarna, eller när du har visat bevis på att du returnerat dem.`,
    },
    rejected: {
      subject: `Uppdatering om din ångerbegäran för order {{ order.name }}`,
      heading: `Uppdatering om din ångerbegäran`,
      callout: `Efter att ha granskat din begäran kan vi tyvärr inte godkänna denna ånger.`,
      intro: `Hej {{ customer.first_name }}, tack för att du kontaktade {{ shop.name }}. Vi har noggrant granskat din ångerbegäran för order {{ order.name }} och kan tyvärr inte godkänna den vid detta tillfälle.`,
      exemptions: `Detta kan inträffa när en begäran görs utanför den lagstadgade ångerfristen på 14 dagar, eller när artiklarna är undantagna från ångerrätten — till exempel personanpassade eller måttbeställda varor, förseglade hälso- eller hygienprodukter vars försegling brutits, eller lättfördärvliga varor.`,
      itemsHeading: `Artiklar i denna begäran`,
      appeal: `Om du vill ha mer information om skälet till detta beslut, eller om du tror att det är ett misstag, hör av dig till oss — vi hjälper dig gärna. Detta beslut påverkar inte dina lagstadgade konsumenträttigheter.`,
    },
  },
};
