// shopify.d.ts only types the `shopify` global for Checkout.jsx (and is
// regenerated by the Shopify CLI, so it shouldn't be hand-edited). The
// runtime injects `shopify` as a true global before any module in this
// bundle runs, so every other file under src/ can reference it directly
// without an import — this declares that for the rest of the program.
declare global {
  const shopify: import('@shopify/ui-extensions/customer-account.order-status.block.render').Api;

  // `process` isn't a real global in the extension's runtime — referencing
  // it is guarded with try/catch at runtime (see src/lib/config.js).
  // Declared as `any` purely to satisfy the editor/type-checker.
  const process: any;
}

export {};
